#!/bin/sh

# Exportation des fichiers de l'application vers Apache Tomcat.

INITIAL=$PWD
cd $(dirname $0)
DESTINATION=$(realpath "../apache-tomcat/webapps/mediatek/WEB-INF")

echo "Exportation du fichier web.xml..."
if [ -f $DESTINATION/web.xml ]
then
    rm $DESTINATION/web.xml
fi
cp ../web.xml $DESTINATION/

echo "Exportation des pages JSP..."
if [ -d $DESTINATION/jsp ]
then
    rm -rf $DESTINATION/jsp
fi
cp -r ../jsp $DESTINATION/

if [ ! -f $DESTINATION/lib/mediatek.jar ]
then
    echo "Exportation de la librairie Mediatek..."
    if [ ! -d $DESTINATION/lib ]
    then
        mkdir $DESTINATION/lib
    fi
    cp ../lib/mediatek.jar $DESTINATION/lib/
fi

echo "Fini."
cd $INITIAL