#!/bin/sh

# Démarrage d'Apache Tomcat et ouverture de l'accueil de la Mediatek.

INITIAL=$PWD
cd $(dirname $0)

echo "Exportation des dernières modifications..."
./exporter

echo "Démarrage d'Apache Tomcat..."
sudo ../apache-tomcat/bin/startup.sh
if [ ! $? -eq 0 ]
then
    echo "Le démarrage d'Apache Tomcat a échoué."
    exit
fi

echo "Démarrage de MySQL via XAMPP..."
sudo /opt/lampp/xampp start

echo "Ouverture de la Mediatek sur le navigateur..."
python -mwebbrowser http://localhost:8080/mediatek/test

echo "Fini."
cd $INITIAL